language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: uNQU8u0A0k67HH/Nqko1JZITTowGXogajssOlZNImuPjWbMmlWwhRzW0a4USRps0jX6OcWkiNk87judl/zbwNmDXMRsMfhcE9z+xnkGfEmI4hcNec0Gd9HDPO89Uc8X9lE/uFACc1TLbpVK4J0OTULl6UUb5lfEtrSCNu0mYzCl2IwUILUBt1xlv6Z9Dc8uiT9nLU+eJ6nHcqPcqoAxTGgbknjVTNUmKQveVOzij4EdIXWP8Xg5zh3DLZ7AL/BbvQwppZKI0nA5SclSArlCrknBUeIzy+EGMGhQi/dMxvqfB+UBhxK0v2iuSbyhkEo1EswZo4rl2lLBl3GAycUspkNCziaFYBtYDC6i7ypViCge7vItgmlxZ/3M/3T939DC1GlLCCjAi1dG/dOzZL5oAWGsv7Oqr0KBphLyqMtXFoGTZHaU8Kt7E5pNBcFXlfGRvHF1FFqCepjrstbQNhEloCtPdywFj3hHgZqYsLz2EzposZJgsJURy2hLxSclhRBt2xwPaEFnAg+O+lyHWmfmQTSNvN/00IyHOkpPzd5WiOZyYA/JZNdlMUeepxAMUL0g4rkRPt471PDi5vzLmXml1acpLcSQXg9IaMgF8X5/vTWQjR1gt94OT5Qin9WfPDM08jwLLiC6lvW1l4knB7pk3xJDFF3f2uNdcHjlH93vORSw=
  app: shrouded-lowlands-90709
  on:
    repo: azhoque/fullstack-capstone
